//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid PlayerAI = new Guid("fb35e8ab-6f2c-4d94-b6f4-c656562e9b21");

    }
}
